security:
    # Configure the password hashers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Define user providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    # Define firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            stateless: true  # Stateless because we are using JWT for API

            # Register the custom authenticator
            custom_authenticator: App\Security\ApiTokenAuthenticator

    # Control access for large sections of your site
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/process-purchase, roles: IS_AUTHENTICATED_FULLY }
